# Generated by Django 3.2.3 on 2021-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
